### ISSUE TITLE
Rendering issues on Firefox

### ISSUE THREAD

**Issue by tomByrer** [gillkyle/card-surge#2]
Tested on Fx Developer Edition 62.0b4  Win10, 4k monitor
Hover Styles button is blocked, everything else works

![card surge sh 2018-07-03 at 15 36 38-fullpage](https://user-images.githubusercontent.com/1308419/42243992-c877a538-7ed8-11e8-8330-dcfa606d33aa.png)

Works fine on Chrome & Edge.
Thanks for your too; inspiring!

**Comment by gillkyle** [comment]
Thanks @tomByrer, a pull request by @poeti8 earlier (#1) should resolve this.

The new version of master was just deployed, thanks for reporting the issue 🙂
